server.port=${PORT:8080}

groq.api.key=${GROQ_API_KEY:}
groq.api.url=https://api.groq.com

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB