server.port=${PORT:8080}
app.upload.dir=uploads
app.python.script=scripts/transcribe.py
python.command=python3

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
