server.port=8080
app.upload.dir=backend/uploads
app.python.script=backend/scripts/transcribe.py
python.command=python3

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
